name: Build & Deploy

on:
  push:
    branches: [mainx]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # Ip address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          key: ${{ secrets.SSH_KEY }} # Private key of the server should be in /home/isaac/.ssh/id_rsa
          script: |
            eval $(ssh-agent -s)
            ssh-add /home/ec2-user/.ssh/id_rsa_github
            cd server
            git checkout main
            git pull
            docker-compose up -d --no-deps --build server
            echo 'Successfully Deployed'
